### Sorting and filtering with Pokemon data

In [ ]:
#importing libraries
import numpy as np
import pandas as pd

In [118]:
df = pd.read_csv("pokemon2.csv", skipinitialspace=True)
df.info()
df

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    str
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    str
 24  classfication      801 non-null    str
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    str
 30  name               801 non-null    str
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    str
 37  type2              417 non-null    str
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), str(7)
memory usage: 256.7 KB

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

#### 1. How many Pokemons exist with an Attack value greater than 150?

In [67]:
df.loc[df['sp_attack'] > 150].shape

# another method
df.query('sp_attack > 150').shape

(14, 41)

#### 2. Select all pokemons with a Speed of 10 or less

In [68]:
df.loc[df['speed'] <= 10].shape

(6, 41)

#### 3. How many Pokemons have a Sp. Def value of 25 or less?

In [69]:
df.loc[df['sp_defense'] <= 25].shape

(17, 41)

#### 4. Select all the Legendary pokemons

In [70]:
legendary_df = df.loc[df['is_legendary'] == True].shape
legendary_df

(70, 41)

#### 5. Find the outlier

In [71]:
df.sort_values(by='sp_defense', ascending=False).head()

# sort by multiple criteria
df.sort_values(by=['sp_defense', 'speed'], ascending=[False, True]).head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
212,"['Sturdy', 'Gluttony', 'Contrary']",1.00,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,50.0,213,10,230,5,bug,rock,20.5,2,0
377,"['Clear Body', 'Ice Body']",1.00,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,...,NaN,378,100,200,50,ice,NaN,175.0,3,1
381,['Drizzle'],1.00,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,NaN,382,180,160,90,water,NaN,352.0,3,1
670,"['Flower Veil', 'Symbiosis']",0.50,0.5,0.0,1.0,1.0,0.5,1.0,1.0,1.0,...,0.0,671,112,154,75,fairy,NaN,10.0,6,0
249,"['Pressure', 'Regenerator']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,NaN,250,110,154,90,fire,flying,199.0,2,1

#### 6. How many Fire-Flying Pokemons are three?

In [72]:
df.loc[(df['type1'] == 'fire') & (df['type2'] == 'flying')]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
5,"['Blaze', 'Solar Power']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,88.1,6,159,115,100,fire,flying,90.5,1,0
145,"['Pressure', 'Flame Body']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,NaN,146,125,85,90,fire,flying,60.0,1,1
249,"['Pressure', 'Regenerator']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,NaN,250,110,154,90,fire,flying,199.0,2,1
661,"['Flame Body', 'Gale Wings']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,50.0,662,56,52,84,fire,flying,16.0,6,0
662,"['Flame Body', 'Gale Wings']",0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,50.0,663,74,69,126,fire,flying,24.5,6,0
740,['Dancer'],0.25,1.0,1.0,2.0,0.5,0.5,0.5,1.0,1.0,...,24.6,741,98,70,93,fire,flying,3.4,7,0

#### 7. How many 'Poison' pokemons are across both types?

In [73]:
df.loc[(df['type1'] == 'poison') | (df['type2'] == 'poison')].shape

(64, 41)

#### 8. What pokemon of Type 1 Ice has the strongest defense?

In [74]:
df.loc[
    (df['type1'] == 'ice') &
    (df['sp_defense'] == df.loc[df['type1'] == 'ice', 'sp_defense'].max())
]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
377,"['Clear Body', 'Ice Body']",1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,...,NaN,378,100,200,50,ice,NaN,175.0,3,1

#### 9. What's the most common type of Legendary Pokemons?

In [75]:
df.loc[df['is_legendary'] == 1, 'type1'].value_counts()

type1
psychic     17
dragon       7
water        6
steel        6
electric     5
fire         5
rock         4
grass        4
normal       3
dark         3
bug          3
ice          2
ground       2
ghost        1
flying       1
fairy        1
Name: count, dtype: int64

#### 10. What's the most powerful pokemon from the first 3 generations, of type water?

In [87]:
df.loc[
    (df['type1'] == 'water') &
    (df['generation'].isin([1, 2, 3]))
].sort_values(by='generation', ascending=False).shape

(70, 41)

#### 11. Select most powerful Fire-type pokemons

In [92]:
df.loc[
    (df['type1'] == 'fire') & (df['sp_attack'] >= 100)
].sort_values(by='sp_attack', ascending=False).shape

(17, 41)

#### 13. Select all Water-type, Flying-type pokemons

In [95]:
df.loc[(df['type1'] == 'water') & (df['type2'] == 'flying')]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
129,"['Intimidate', 'Moxie']",0.5,1.0,1.0,4.0,1.0,0.5,0.5,1.0,1.0,...,50.0,130,70,130,81,water,flying,235.0,1,0
225,"['Swift Swim', 'Water Absorb', 'Water Veil']",0.5,1.0,1.0,4.0,1.0,0.5,0.5,1.0,1.0,...,50.0,226,80,140,70,water,flying,220.0,2,0
277,"['Keen Eye', 'Hydration', 'Rain Dish']",0.5,1.0,1.0,4.0,1.0,0.5,0.5,1.0,1.0,...,50.0,278,55,30,85,water,flying,9.5,3,0
278,"['Keen Eye', 'Drizzle', 'Rain Dish']",0.5,1.0,1.0,4.0,1.0,0.5,0.5,1.0,1.0,...,50.0,279,95,70,65,water,flying,28.0,3,0
457,"['Swift Swim', 'Water Absorb', 'Water Veil']",0.5,1.0,1.0,4.0,1.0,0.5,0.5,1.0,1.0,...,50.0,458,60,120,50,water,flying,65.0,4,0
579,"['Keen Eye', 'Big Pecks', 'Hydration']",0.5,1.0,1.0,4.0,1.0,0.5,0.5,1.0,1.0,...,50.0,580,44,50,55,water,flying,5.5,5,0
580,"['Keen Eye', 'Big Pecks', 'Hydration']",0.5,1.0,1.0,4.0,1.0,0.5,0.5,1.0,1.0,...,50.0,581,87,63,98,water,flying,24.2,5,0

#### 14. Select specific columns of Legendary pokemons of type Fire

In [ ]:
df.loc[((df['type1'] == 'fire') | (df['type2'] == 'fire')) & (df['is_legendary'] == 1), ['sp_attack', 'generation']]

     sp_attack  generation
145        125           1
243         90           2
249        110           2
484        130           4
493        100           5
642        150           5
720        130           6

#### 15. Select Slow and Fast pokemons

In [99]:
df['speed_rate'] = (df['speed'] / df['speed'].max()) * 100
df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,speed_rate
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,1,65,65,45,grass,poison,6.9,1,0,25.000000
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,2,80,80,60,grass,poison,13.0,1,0,33.333333
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,3,122,120,80,grass,poison,100.0,1,0,44.444444
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,4,60,50,65,fire,NaN,8.5,1,0,36.111111
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,5,80,65,80,fire,NaN,19.0,1,0,44.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,797,107,101,61,steel,flying,999.9,7,1,33.888889
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,798,59,31,109,grass,steel,0.1,7,1,60.555556
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,799,97,53,43,dark,dragon,888.0,7,1,23.888889
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,800,127,89,79,psychic,NaN,230.0,7,1,43.888889
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,801,130,115,65,steel,fairy,80.5,7,1,36.111111

In [107]:
df.loc[(df['speed_rate'] >= 95) | (df['speed_rate'] <= 5)]

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,speed_rate
212,"['Sturdy', 'Gluttony', 'Contrary']",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,213,10,230,5,bug,rock,20.5,2,0,2.777778
385,['Pressure'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,386,95,90,180,psychic,NaN,60.8,3,1,100.000000
445,"['Pickup', 'Thick Fat', 'Gluttony']",1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,...,446,40,85,5,normal,NaN,105.0,4,0,2.777778
770,"['Innards Out', 'Unaware']",1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,771,30,130,5,water,NaN,1.2,7,0,2.777778

#### 16. Find the Ultra Powerful Legendary Pokemon

In [116]:
df.loc[(df['is_legendary'] == 1)].sort_values(by=['sp_attack', 'sp_defense'], ascending=[False, False])

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,speed_rate
149,"['Pressure', 'Unnerve']",2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,150,194,120,140,psychic,NaN,122.0,1,1,77.777778
381,['Drizzle'],1.0,1.0,1.0,2.0,1.0,1.0,0.5,1.0,1.0,...,382,180,160,90,water,NaN,352.0,3,1,50.000000
383,['Air Lock'],0.5,1.0,2.0,1.0,2.0,0.5,0.5,1.0,1.0,...,384,180,100,115,dragon,flying,206.5,3,1,63.888889
795,['Beast Boost'],1.0,1.0,1.0,0.5,1.0,1.0,1.0,0.5,1.0,...,796,173,71,83,electric,NaN,100.0,7,1,46.111111
719,['Magician'],1.0,4.0,1.0,1.0,1.0,0.0,1.0,1.0,4.0,...,720,170,130,80,psychic,ghost,NaN,6,1,44.444444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,['Beast Boost'],1.0,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,798,59,31,109,grass,steel,0.1,7,1,60.555556
793,['Beast Boost'],0.5,0.5,1.0,1.0,2.0,0.5,2.0,4.0,1.0,...,794,53,53,79,bug,fighting,333.6,7,1,43.888889
376,"['Clear Body', 'Sturdy']",1.0,1.0,1.0,1.0,1.0,2.0,0.5,0.5,1.0,...,377,50,100,50,rock,NaN,230.0,3,1,27.777778
789,['Sturdy'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,790,29,131,37,psychic,NaN,999.9,7,1,20.555556
788,['Unaware'],2.0,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,789,29,31,37,psychic,NaN,0.1,7,1,20.555556